# Generated by Django 5.1.6 on 2025-02-24 23:01

from django.db import migrations

def create_default_categories(apps, schema_editor):
    CategoryModel = apps.get_model('notes', 'CategoryModel')
    default_categories = [
        {'name': 'random_thoughts', 'color': '#EF9C66'},
        {'name': 'school', 'color': '#FCDC94'},
        {'name': 'personal', 'color': '#78ABA8'},
    ]
    
    for category in default_categories:
        CategoryModel.objects.get_or_create(
            name=category['name'],
            defaults={'color': category['color']}
        )

def remove_default_categories(apps, schema_editor):
    CategoryModel = apps.get_model('notes', 'CategoryModel')
    CategoryModel.objects.filter(
        name__in=['random_thoughts', 'school', 'personal']
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories,
            reverse_code=remove_default_categories
        ),
    ]
