# Generated by Django 5.1.6 on 2025-03-04 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
